In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 100000
max_steps_per_episode = 1000

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [5]:
rewards_all_episods = []

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            # exploitation
            action = np.argmax(q_table[state, :])
        else:
            # exploration
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        # updating Q table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
        
    # exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episods.append(rewards_current_episode)
    
# Average reward each 1000 episode
reward_per_thosand_episodes = np.split(np.array(rewards_all_episods), num_episodes/1000)
count = 1000
print('==== Average reward per thounsand episods ====\n')
for r in reward_per_thosand_episodes:
    print(count , ' : ' , str(sum(r/1000)))
    count += 1000
    
print('==== Updated Q table ====\n')
print(q_table)

==== Average reward per thounsand episods ====

1000  :  0.05400000000000004
2000  :  0.19600000000000015
3000  :  0.4120000000000003
4000  :  0.5470000000000004
5000  :  0.6160000000000004
6000  :  0.6730000000000005
7000  :  0.6850000000000005
8000  :  0.6790000000000005
9000  :  0.6650000000000005
10000  :  0.6860000000000005
11000  :  0.6610000000000005
12000  :  0.6930000000000005
13000  :  0.7150000000000005
14000  :  0.7000000000000005
15000  :  0.6650000000000005
16000  :  0.6670000000000005
17000  :  0.6820000000000005
18000  :  0.6800000000000005
19000  :  0.6560000000000005
20000  :  0.6860000000000005
21000  :  0.6850000000000005
22000  :  0.7030000000000005
23000  :  0.6900000000000005
24000  :  0.6890000000000005
25000  :  0.6910000000000005
26000  :  0.6590000000000005
27000  :  0.6730000000000005
28000  :  0.6820000000000005
29000  :  0.7080000000000005
30000  :  0.6690000000000005
31000  :  0.6760000000000005
32000  :  0.6970000000000005
33000  :  0.6980000000000005
34

In [ ]:
for episode in range(3):
    state = env.reset()
    done = False
    print('========== EPISODE ',episode+1, ' ============')
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print('YOU\'VE REACHED THE GOAL !!!')
            else:
                print('YOU FELL THROUH A HOLE :(')
            time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
    env.close()

  (Up)
SFFF
FHFH
FFFH
HFFG
